MB.Presentation.Razor/Areas/Administrator/Pages/ArticleCategoryManagement/Create.cshtml.cs
using MB.Application.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.Razor.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class CreateModel : PageModel
    {
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost(CreateArticleCategory command)
        {

            _articleCategoryApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

MB.Presentation.Razor/Areas/Administrator/Pages/ArticleCategoryManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application;
using MB.Application.Contracts;
using MB.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.Razor.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public EditArticleCategory ViewModel { get; set; }
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(EditArticleCategory command)
        {
            ViewModel = _articleCategoryApplication.Get(command.Id);
        }
        public IActionResult OnPost(EditArticleCategory command)
        {
            _articleCategoryApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }

}

MB.Presentation.Razor/Areas/Administrator/Pages/ArticleManagement/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application;
using MB.Application.Contracts;
using MB.Application.Contracts.Article;
using MB.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MB.Presentation.Razor.Areas.Administrator.Pages.ArticleManagement
{
    public class CreateModel : PageModel
    {
        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;
        public List<SelectListItem> Categories { get; set; }
        public CreateModel(IArticleApplication articleApplication,
            IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
            Categories = _articleCategoryApplication.List().Select(x => new SelectListItem(
                x.Title, x.Id.ToString())).ToList();
        }
        public IActionResult OnPost(CreateArticle command)
        {
            _articleApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

MB.Presentation.Razor/Areas/Administrator/Pages/ArticleManagement/Edit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using MB.Application.Contracts;
using MB.Application.Contracts.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MB.Presentation.Razor.Areas.Administrator.Pages.ArticleManagement
{
    public class EditModel : PageModel
    {
        [BindProperty] public EditArticle Article { get; set; }
        public List<SelectListItem> Categories { get; set; }
        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleApplication articleApplication,
            IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
            _articleApplication = articleApplication;
        }

        public void OnGet(int id)
        {
            Categories = _articleCategoryApplication.List().Select(x =>
                new SelectListItem(x.Title, x.Id.ToString())).ToList();
            var article = _articleApplication.Get(id);
            Article = new EditArticle
            {
                ShortDescription = article.ShortDescription,
                ArticleId = article.Id,
                Body = article.Body,
                Title = article.Title,
                PictureUrl = article.PictureUrl,
                ArticleCategoryId = article.ArticleCategoryId
            };
        }

        public IActionResult OnPost()
        {
            _articleApplication.Edit(Article);
            return RedirectToPage("./Index");
        }
    }
}

MB.Presentation.Razor/Areas/Administrator/Pages/ArticleManagement/Index.cshtml.cs
using System.Collections.Generic;
using MB.Application.Contracts.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.Razor.Areas.Administrator.Pages.ArticleManagement
{
    public class IndexModel : PageModel
    {
        public List<ArticleViewModel> Articles { get; set; }
        private readonly IArticleApplication _articleApplication;

        public IndexModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }
        public void OnGet()
        {
            Articles = _articleApplication.GetAll();
        }
        public IActionResult OnPostDelete(int Id)
        {
            _articleApplication.Delete(Id);
            return RedirectToPage("./Index");
        }
        public IActionResult OnPostReactivate(int Id)
        {
            _articleApplication.Reactivate(Id);
            return RedirectToPage("./Index");
        }
    }
}

MB.Presentation.Razor/Areas/Administrator/Pages/ArticleManagement/Create.cshtml
@page
@model MB.Presentation.Razor.Areas.Administrator.Pages.ArticleManagement.CreateModel
@{
}
<div class="card-body">
    <div class="row border">
        <div class="col-md-12">
            <div class="row justify-content-between p-4" style="background-color: #e7e1e1">
                <h1 class="display-4"> Create a new Article</h1>

            </div>
            <form class="form-group py-4" method="post">
                <div class="col-md-8">
                    <label class="col-md-8 p-0" for="title"> Title </label>
                    <input class="col-md-8 border rounded" type="text" name="title" />
                </div>
                <div class="col-md-8">
                    <label class="col-md-8 p-0" for="ShortDescription"> Short Description </label>
                    <textarea class="col-md-8 border rounded" rows="3" type="text" name="ShortDescription"></textarea>
                </div>
                <div class="col-md-8">
                    <label class="col-md-8 p-0" for="PictureUrl"> Picture Url </label>
                    <input class="col-md-8 border rounded" type="text" name="PictureUrl" />
                </div>
                <div class="col-md-8">
                    <label class="col-md-8 p-0" for="body"> Body </label>
                    <textarea class="col-md-8 border rounded" rows="5" type="text" name="body"></textarea>
                </div>
                <div class="col-md-8">
                    <select asp-items="@Model.Categories"
                            name="ArticleCategoryId" id="ArticleCategoryId"> Select a category:
                       <option value="0"> Select a category</option>
                    </select>
                </div>
                <div class="col-md-4 justify-content-between">
                    <button type="submit" class="btn btn-success">Create</button>
                    <a class="btn btn-dark m-4" asp-page="./Index"> Go Back</a>
                </div>
            </form>


        </div>
    </div>
</div>

MB.Presentation.Razor/Areas/Administrator/Pages/ArticleManagement/Edit.cshtml
@page "{id:int}"
@model MB.Presentation.Razor.Areas.Administrator.Pages.ArticleManagement.EditModel
@{
}
<div class="card-body">
    <div class="row border">
        <div class="col-md-12">
            <div class="row justify-content-between p-4" style="background-color: #e7e1e1">
                <h1 class="display-4"> Edit @Model.Article.Title</h1>

            </div>
            <form class="form-group py-4" method="post">
                <div class="col-md-8">
                    <input class="col-md-8 border rounded" type="hidden"
                           asp-for="Article.ArticleId"/>
                </div>
                <div class="col-md-8">
                    <input class="col-md-8 border rounded" type="hidden"
                           asp-for="Article.ArticleCategoryId"/>
                </div>
                <div class="col-md-8">
                    <label class="col-md-8 p-0" asp-for="Article.Title"> Title </label>
                    <input class="col-md-8 border rounded" type="text"
                           asp-for="Article.Title"/>
                </div>
                <div class="col-md-8">
                    <label class="col-md-8 p-0" asp-for="Article.ShortDescription"> Short Description </label>
                    <textarea class="col-md-8 border rounded" rows="3" type="text"
                              asp-for="Article.ShortDescription" ></textarea>
                </div>
                <div class="col-md-8">
                    <label class="col-md-8 p-0" asp-for="Article.PictureUrl"> Picture Url </label>
                    <input class="col-md-8 border rounded" type="text"
                           asp-for="Article.PictureUrl"/>
                </div>
                <div class="col-md-8">
                    <label class="col-md-8 p-0" asp-for="Article.Body"> Body </label>
                    <textarea class="col-md-8 border rounded" rows="5" type="text" asp-for="Article.Body"
                              value="@Model.Article.Body"></textarea>
                </div>
                <div class="col-md-8">
                    <label asp-for="Article.ArticleCategoryId"></label>
                    <select asp-items="@Model.Categories" asp-for="Article.ArticleCategoryId">
                        <option value=""> Select a category</option>
                    </select>
                </div>
                <div class="col-md-4 justify-content-between">
                    <button type="submit" class="btn btn-success" value="@Model.Article.ArticleId">Save Changes</button>
                    <a class="btn btn-dark m-4" asp-page="./Index"> Go Back</a>
                </div>
            </form>


        </div>
    </div>
</div>

MB.Presentation.Razor/Areas/Administrator/Pages/ArticleManagement/Index.cshtml
@page
@model MB.Presentation.Razor.Areas.Administrator.Pages.ArticleManagement.IndexModel
@{
}
<div class="text-center">
    <div class="d-flex col-md-12 justify-content-between p-4" style="background-color: #e7e1e1">
        <h1> Article </h1>
        <a class="btn btn-success align-self-sm-center" asp-page="./Create"> Create a new article</a>
    </div>
    <div class="p-0">
        <table class="table table-bordered">
            <thead>
                <tr class="text-nowrap">
                    <th>Article Id</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>StatusHelper</th>
                    <th>Creation Date</th>
                    <th>Manage</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in @Model.Articles)
                {
                    <tr>
                        <td> @item.Id </td>
                        <td scope="row"> @item.Title</td>
                        <td> @item.ArticleCategory</td>
                        <td>
                            @if (item.IsDeleted)
                            {
                                <i class="fa fa-ban fa-2x text-danger"></i>
                            }
                            else
                            {
                                <i class="fa fa-check-square fa-2x text-success"></i>
                            }
                        </td>
                        <td> @item.CreationTime</td>
                        <td>
                            <div class="d-flex justify-content-center">
                                <a class="btn btn-warning mx-1" asp-page="./Edit" asp-route-id="@item.Id"> Modify</a>
                                @if (item.IsDeleted)
                                {
                                    <form method="post" class="mx-1">
                                        <button class="btn btn-success"
                                                type="submit" asp-page-handler="Reactivate">
                                            Reactivate
                                        </button>
                                        <input type="hidden" value="@item.Id" name="Id" />
                                    </form>
                                }
                                else
                                {

                                    <form method="post" class="mx-1">
                                        <button class="btn btn-danger"
                                                type="submit" asp-page-handler="Delete">
                                            Delete
                                        </button>
                                        <input type="hidden" value="@item.Id" name="Id" />
                                    </form>
                                }
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>